class CONFIG:
    MINIMUM_NAME_LENGTH = 3
    NAME_LENGTH = 50
    IMAGE_EXTENSIONS = ["png", "jpg"]
    MINIMUM_IMAGE_SIZE = 5000
    MAXIMUM_IMAGE_SIZE = 20485760
    UPLOAD_DIRECTORY = "maps"
    THUMBNAIL_SIZE = 512
    THUMBNAIL_FORMAT = "PNG"
    THUMBNAIL_DIRECTORY = UPLOAD_DIRECTORY + "/thumbnails"
